Datasets:
  dev:
    batch_size: 32
    class_name: PaddedDatasetLoader
    dataset:
      alignment_root: data/scribblelens.paths.1.4.zip
      class_name: egs.scribblelens.data.ScribbleLensDataset
      split: test
      transcript_mode: 5
      vocabulary: egs/scribblelens/tasman.alphabet.plus.space.mode5.json
    rename_dict:
      image: features
      scribe_id: side_info
  train:
    batch_size: 32
    class_name: FixedDatasetLoader
    dataset:
      chunk_len: 128
      class_name: distsup.data.ChunkedDataset
      dataset:
        alignment_root: data/scribblelens.paths.1.4.zip
        class_name: egs.scribblelens.data.ScribbleLensDataset
        split: train
        transcript_mode: 5
        vocabulary: egs/scribblelens/tasman.alphabet.plus.space.mode5.json
      drop_fields:
      - text
      - alignment_rle
      - page_side
      - page
      oversample: 4
      training: true
      varlen_fields:
      - image
      - alignment
    num_workers: 4
    pin_memory: true
    rename_dict:
      image: features
      scribe_id: side_info
    shuffle: true
Model:
  bottleneck:
    class_name: distsup.modules.bottlenecks.VQBottleneck
    log_input_norms: true
    normalization: batch_norm
    num_tokens: 4096
  bottleneck_latent_dim: 128
  class_name: distsup.models.representation_learners.RepresentationLearner
  encoder:
    class_name: distsup.modules.encoders.DeepSpeech2
    conv_kernel_sizes:
    - - 3
      - 3
    - - 5
      - 5
    - - 3
      - 3
    - - 3
      - 3
    - - 3
      - 3
    - - 3
      - 3
    - - 3
      - 2
    conv_nonlinearity: leakyrelu
    conv_num_features:
    - 64
    - 128
    - 256
    - 256
    - 512
    - 512
    - 512
    conv_strides:
    - - 1
      - 2
    - - 2
      - 2
    - - 1
      - 1
    - - 1
      - 2
    - - 1
      - 1
    - - 1
      - 2
    - - 1
      - 1
    rnn_bias: true
    rnn_bidirectional: true
    rnn_dropout: 0
    rnn_hidden_size: 32
    rnn_nb_layers: 2
    rnn_normalization: batch_norm
    rnn_projection_size: 32
    rnn_residual: true
    rnn_subsample:
    - 1
    - 1
  image_height: 32
  probes:
    bottleneck:
      bp_to_main: false
      layer: bottleneck
      predictor:
        aggreg: 3
        class_name: distsup.modules.predictors.FramewisePredictor
        use_two_layer_predictor: true
      target: alignment
    bottleneck_ctc:
      bp_to_main: false
      layer: bottleneck
      predictor:
        aggreg: 3
        class_name: distsup.modules.predictors.CTCPredictor
      target: alignment
    input:
      bp_to_main: false
      layer: input_layer
      predictor:
        aggreg: 3
        class_name: distsup.modules.predictors.FramewisePredictor
        use_two_layer_predictor: true
      target: alignment
    latent_mixer:
      bp_to_main: false
      layer: latent_mixer
      predictor:
        aggreg: 3
        class_name: distsup.modules.predictors.FramewisePredictor
        use_two_layer_predictor: true
      target: alignment
  reconstructor:
    class_name: distsup.modules.reconstructors.ColumnGatedPixelCNN
    hid_channels: 64
  side_info_encoder: null
Trainer:
  checkpointer:
    every_n_hours: 1
  codebook_lr: 0.02
  gradient_clipping:
    clip_norm: 10.0
  learning_rate: 0.002
  learning_rate_scheduler:
    class_name: torch.optim.lr_scheduler.ReduceLROnPlateau
    factor: 0.8
    min_lr: 2.0e-05
    patience: 3
  num_epochs: 150
  optimizer_kwargs:
    betas:
    - 0.9
    - 0.999
  optimizer_name: Adam
  output_frequency: 50
  polyak_decay:
  - 0.998
  weight_noise: 0.0
  weight_noise_start_iteration: 10000
